services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-image-resize'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI